### ISSUE TITLE
Visibility/access issue with some plugins

### ISSUE THREAD

**Issue by FPAdministrator** [FutureProcessing/glpi-fpsaml#1]
Following plugins are not accessible from drop-down menus after installing FP SAML:
- Racks
- OCS Inventory NG
- SIM Cards

User can access those plugins by using direct links to pages related to them. Another way is to enable and disable any plugin then during user session  (links to plugins will appear in menus).

**Comment by prybak** [comment]
This issue applies to all plugins that modifies menu/add additional functionality to existing forms/pages.
