### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by goupiN008** [FutureProcessing/glpi-fpsaml#10]
hello 
I need to integrate GLPI with ADFS via saml. when I install plugin fpsaml and enable in plugin menu it show HTTP ERROR 500 . please tell me the solution

I did following the instruction that clone plugin to plugin directory ,composer install and cp cfg.php file then I enable in plugin menu in web 

my server : ubuntu 18.04 
Thanks

**Comment by prybak** [comment]
Seems obsolete. Closing.
