### ISSUE TITLE
SAML Error The action you have requested is not allowed.

### ISSUE THREAD

**Issue by terenceRC** [FutureProcessing/glpi-fpsaml#3]
Hi I have used FPSAML and linked it to the new GOOGLE IDP rather than ADFS.

Every works well except for 2 things
1) After i click on the link and the SAML response is ok I get this response from GLPI "The action you have requested is not allowed." I googled it and it seems to be CSRF. i disabled it in GLPI and rather than logging in, it just sends me to the login page. I dont know what to do.

2) In the event that the user does not exist in GLPI, I would like a new user to be created. Is this possible? 

Thanks so much!

**Comment by prybak** [comment]
Plugin was not tested, planned for Google IDP.
