### ISSUE TITLE
Support of GLPI v9.1

### ISSUE THREAD

**Issue by v01ded** [FutureProcessing/glpi-fpsaml#4]
Hi,

Great work on enabling SAML sso for GLPI. Any plans to get it working on the latest GLPI v9.1? Thanks!

Stanley Lim

**Comment by prybak** [comment]
Hi Stanley,
Yes, we plan to migrate plugin to 9.1 but we are still waiting for more stable version :). I think that 9.1.1 is already planned as 9.1 contains a lot of bugs.

**Comment by v01ded** [comment]
Great to know that you would continue to develop the plugin for 9.1.1. Any chance of doing a version for 9.1? I'm planning to try to see if I can get it to work with AZURE AD which support SAML 2.0 Thanks!  Regards Stanley Lim

**Comment by dsever** [comment]
Hi,

Any news about support for SAML authentication over ADFS using GLPI 9.1.1.?

Thanks
Dubravko

**Comment by prybak** [comment]
Plugin works for GLPI 9.1.x ;). We are running it at 9.1.6 currently. No changes in code are necessary apart of changing the check value for version.
