### ISSUE TITLE
GLPI 9.1.1 glpi-fpsaml is not visible in plugins menu 

### ISSUE THREAD

**Issue by falcon78921** [FutureProcessing/glpi-fpsaml#5]
Hello FutureProcessing,

In my production environment, I have GLPI 9.1.1 operating tremendously. We have many applications that are SAML 2.0 compliant, and we fabricated a portal that provides SSO to these internal services. 

When I install the glpi-fpsaml plugin (per the directions stated), the plugin doesn't seem to appear in  GLPI's Plugins submenu. I have checked web permissions multiple times, executed chown -R www-data:www-data, etc. I cannot seem to get the application within GLPI's dashboard. 

If the problem seems like a permission's issue (I think it still might have something to do with that), is there anything you might recommend for me to try? I appreciate all assistance offered.

**Comment by falcon78921** [comment]
Here is some more information about what I'm experiencing. I have performed all of the installation steps per the directions on the project's homepage.

I still cannot see the plugin within GLPI's Plugins menu.

Here are the pages I'm trying to request and the errors associated:

**acs.php**
. . .
[Tue Jun 13 15:53:47.638821 2017] [:error] [pid 13507] [client 10.10.12.45:37264] PHP Fatal error:  Uncaught Assert\\InvalidArgumentException: Value "" was expected to be a valid URL starting with http or https in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php:285\nStack trace:\n#0 /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php(1602): Assert\\Assertion::createException('', 'Value "" was ex...', 203, NULL)\n#1 /var/www/glpi2/plugins/glpi-fpsaml/src/Fp/Saml/Config/Idp.php(87): Assert\\Assertion::url('')\n#2 /var/www/glpi2/plugins/glpi-fpsaml/_bootstrap.php(26): Fp\\Saml\\Config\\Idp->setIssuerUrl('')\n#3 /var/www/glpi2/plugins/glpi-fpsaml/front/acs.php(15): require_once('/var/www/glpi2/...')\n#4 {main}\n  thrown in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php on line 285, referer: https://xxxxxxxxxxx.net/glpi2/plugins/glpi-fpsaml/front/
. . .
**meta.php**
. . .
[Tue Jun 13 15:54:46.661977 2017] [:error] [pid 13507] [client 10.10.12.45:37276] PHP Fatal error:  Uncaught Assert\\InvalidArgumentException: Value "" was expected to be a valid URL starting with http or https in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php:285\nStack trace:\n#0 /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php(1602): Assert\\Assertion::createException('', 'Value "" was ex...', 203, NULL)\n#1 /var/www/glpi2/plugins/glpi-fpsaml/src/Fp/Saml/Config/Idp.php(87): Assert\\Assertion::url('')\n#2 /var/www/glpi2/plugins/glpi-fpsaml/_bootstrap.php(26): Fp\\Saml\\Config\\Idp->setIssuerUrl('')\n#3 /var/www/glpi2/plugins/glpi-fpsaml/front/meta.php(7): require_once('/var/www/glpi2/...')\n#4 {main}\n  thrown in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php on line 285, referer: https://xxxxxxxxxxxxxxx.net/glpi2/plugins/glpi-fpsaml/front/
. . .
**slo.php**
. . .
[Tue Jun 13 15:55:30.976618 2017] [:error] [pid 22203] [client 10.10.12.45:37290] PHP Fatal error:  Uncaught Assert\\InvalidArgumentException: Value "" was expected to be a valid URL starting with http or https in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php:285\nStack trace:\n#0 /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php(1602): Assert\\Assertion::createException('', 'Value "" was ex...', 203, NULL)\n#1 /var/www/glpi2/plugins/glpi-fpsaml/src/Fp/Saml/Config/Idp.php(87): Assert\\Assertion::url('')\n#2 /var/www/glpi2/plugins/glpi-fpsaml/_bootstrap.php(26): Fp\\Saml\\Config\\Idp->setIssuerUrl('')\n#3 /var/www/glpi2/plugins/glpi-fpsaml/front/slo.php(11): require_once('/var/www/glpi2/...')\n#4 {main}\n  thrown in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php on line 285, referer: https://xxxxxxxxxxxxxxxxxx.net/glpi2/plugins/glpi-fpsaml/front/
. . .
**ssoRequest.php**
. . .
[Tue Jun 13 15:55:59.825465 2017] [:error] [pid 26014] [client 10.10.12.45:37294] PHP Fatal error:  Uncaught Assert\\InvalidArgumentException: Value "" was expected to be a valid URL starting with http or https in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php:285\nStack trace:\n#0 /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php(1602): Assert\\Assertion::createException('', 'Value "" was ex...', 203, NULL)\n#1 /var/www/glpi2/plugins/glpi-fpsaml/src/Fp/Saml/Config/Idp.php(87): Assert\\Assertion::url('')\n#2 /var/www/glpi2/plugins/glpi-fpsaml/_bootstrap.php(26): Fp\\Saml\\Config\\Idp->setIssuerUrl('')\n#3 /var/www/glpi2/plugins/glpi-fpsaml/front/ssoRequest.php(4): require_once('/var/www/glpi2/...')\n#4 {main}\n  thrown in /var/www/glpi2/plugins/glpi-fpsaml/vendor/beberlei/assert/lib/Assert/Assertion.php on line 285, referer: https://mytrucker.norwalktruckers.net/glpi2/plugins/glpi-fpsaml/front/
. . .

Again, I think its either I'm missing something (that was not in the directions) or the program is missing some PHP dependencies.

I hope this will help other users understand my issue. Thanks.

**Comment by Kailas10** [comment]
Hi,
If you read the error proper the path you are passing is not starting with **http or https**.
check the **_bootstrap.php** file on line number 12.
$baseUrl = $CFG_GLPI['url_base'] . '/plugins/glpi-fpsaml/front/';

`$CFG_GLPI['url_base']` it has empty value.

so all file path are not start with **http or https**
```
$spConfig = new Sp();
$spConfig->setSpCertificate($config['spCertificate'])
    ->setSpPrivateKey($config['spPrivateKey'])
    ->setSpMetadataUrl($baseUrl . 'meta.php')
    ->setSpSingleLogoutUrl($baseUrl . 'slo.php')
    ->setSpAssertionConsumerUrl($baseUrl . 'acs.php');
```

**Comment by falcon78921** [comment]
Thanks for the feedback @Kailas10. It's been a long time since I've looked at this issue.

**Comment by falcon78921** [comment]
@Kailas10 I'm still having issues, even when populating the ```$baseUrl``` with a full URL path. 

This issue is no longer relevant, to me. Going to close.
