### ISSUE TITLE
Works with fusion inventory?

### ISSUE THREAD

**Issue by derricksmith** [FutureProcessing/glpi-fpsaml#6]
Not an issue, just wanted to put this somewhere in case you want to include or others have the same issue.

I was not unable to get any agents to communicate with the server when FP-Saml was enabled.  I found a quick work around by wrapping the main authentication check in an if statement that checks for the fusion inventory variables.

Is there a more elegant way to accomplish this?

setup.php

        $rawdata = file_get_contents("php://input");
	$action = filter_input(INPUT_GET, "action");
	$machineid = filter_input(INPUT_GET, "machineid");

	if (class_exists('PluginFusioninventoryCommunication') && $_SERVER['REQUEST_URI'] == '/plugins/fusioninventory/' && ((!empty($action) && !empty($machineid)) || !empty($rawdata))){
		return;	
	} else {
		if (!PluginFpsamlMain::isUserAuthenticated()) {
			if (ServiceContainer::getInstance()->getSsoStateStore()->get()) {
				PluginFpsamlMain::tryLogin(isset($_GET['redirect']) ? $_GET['redirect'] : null);
			} else {
				if (ServiceContainer::getInstance()->getConfig()->isForceRedirectToSignInPage()) {
					$redirectUrl = $_SERVER['REQUEST_URI'] !== '/' ? $CFG_GLPI['url_base'] . $_SERVER['REQUEST_URI'] : null;
					$_SERVER['REQUEST_URI'];

					PluginFpsamlMain::ssoRequest($redirectUrl);
				}
			}
		} else {
			if (strpos($_SERVER['PHP_SELF'], '/logout.php') !== false && ServiceContainer::getInstance()->getSsoStateStore()->get()) {
				PluginFpsamlMain::sloRequest();
			} elseif ($_SERVER['REQUEST_URI'] === '/') {
				PluginFpsamlMain::redirectToMainPage();
			}
		}
	
	}

**Comment by prybak** [comment]
We haven't tested it against FI and we are not planning to do it.
